sudo: true

language: java

jdk: oraclejdk8

matrix:
  include:
  - env: TARGET_FILE_NAME=neon

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

addons:
  apt:
    packages:
    - mutter

before_script:
 - sh -e /etc/init.d/xvfb start
 - mutter --sm-disable --replace 2> mutter.err &
 
script:
 - export
 - mvn -f swtbot.example.parent/pom.xml clean verify -Dtarget-file-name=$TARGET_FILE_NAME
