sudo: false

language: java

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

env: DISPLAY=:99.0

install: true

addons:
  apt:
    packages:
    - mutter

before_script:
 - sh -e /etc/init.d/xvfb start
 - mutter --sm-disable --replace 2> metacity.err &
 
script:
 - export
 - mvn -f swtbot.example.parent/pom.xml clean verify
