sudo: false

language: java

jdk: oraclejdk8

matrix:
  include:
    # always build this environment
  - env: TARGET_FILE_NAME=oxygen DISPLAY=:99.0
    # only on PR
  - env: TARGET_FILE_NAME=photon DISPLAY=:99.0
    if: type IN (pull_request)
  - env: TARGET_FILE_NAME=neon DISPLAY=:99.0
    if: type IN (pull_request)
  - env: TARGET_FILE_NAME=mars DISPLAY=:99.0
    if: type IN (pull_request)

cache:
  directories:
  - $HOME/.m2

install: true

addons:
  apt:
    packages:
    - mutter

before_script:
 - sh -e /etc/init.d/xvfb start
 - mutter --sm-disable --replace 2> mutter.err &
 
script:
 - export
 - mvn -f swtbot.example.parent/pom.xml clean verify -Dtarget-file-name=$TARGET_FILE_NAME

after_failure:
 - cat swtbot.example.tests/target/work/data/.metadata/.log