sudo: false

language: java

jdk: oraclejdk8

matrix:
  include:
  - env: PROFILE=neon DISPLAY=:99.0

cache:
  directories:
  - $HOME/.m2

install: true

addons:
  apt:
    packages:
    - mutter

before_script:
 - sh -e /etc/init.d/xvfb start
 - mutter --sm-disable --replace 2> mutter.err &
 
script:
 - export
 - echo $PROFILE
 - mvn -f swtbot.example.parent/pom.xml -P "$PROFILE" clean verify
